url: http://www.mrc-cambodiatransport.com
#baseurl: /

# Site settings
title: Mr. C's Cambodia Transport
email: mail@mrc-cambodiatransport.com
description: Tuk-tuk, car, and minivan services in Phnom Penh and the rest of Cambodia by Mr. C. English speaking
driver and tour organizer. Always ready to go the extra mile for my customers.
preview_image: http://www.mrc-cambodiatransport.com/img/site_preview.jpg

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mr. C
  pic: mrc
  position: Driver and tour organizer
  social:
    - title: facebook
      url: https://www.facebook.com/pages/Mr-Cs-Cambodia-Transport/430659350373852


# Build settings
markdown: kramdown
permalink: pretty


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-61043662-1