url: http://mrc-cambodiatransport.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Mr. C
email: mail@mrc-cambodiatransport.com
description: Tuk-tuk, car, and minivan services in Phnom Penh and the rest of Cambodia by Mr. C. English speaking driver and tour organizer.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mr. C
  pic: mrc
  position: Driver and tour organizer
  social:
    - title: facebook
      url: https://www.facebook.com/pages/Mr-Cs-Cambodia-Transport/430659350373852


# Build settings
markdown: kramdown
permalink: pretty